[project]
name = "transformers-for-sentiment-analysis"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.1.0",
    "polars>=1.17.1",
    "transformers[torch]>=4.47.0",
]

# [[tool.uv.index]]
# name = "pytorch-cpu"
# url = "https://download.pytorch.org/whl/cpu"
# explicit = true
#
# [tool.uv.sources]
# torch = [{ index = "pytorch-cpu", marker = "platform_system != 'Darwin'" }]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # print is fine
    "T201",
    # documentation is hard
    "D100",
    "D103",
    # conflicts with D211
    "D203",
    # conflicts with D212
    "D213",
    # unnecessary perf optimization
    "TC002",
    # commented-out code is fine
    "ERA001",
    # can't be used with formatter
    "COM812",
    "ISC001",
]
